In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
data = pd.read_csv('https://raw.githubusercontent.com/kdemertzis/EKPA/main/Data/phishing_dataset.csv', delimiter=',')

In [ ]:
data = data.sample(frac=1).reset_index(drop=True)
data.head()

Domain  Have_IP  Have_At  URL_Length  URL_Depth  Redirection  \
0  albel.intnet.mu        0        0           1          2            0   
1   allrecipes.com        0        0           1          3            0   
2      twitter.com        0        0           1          1            0   
3       medium.com        0        0           1          2            0   
4   therockacc.org        0        0           1          4            0   

   https_Domain  TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  \
0             0        0              0           0            0           0   
1             0        0              0           0            1           1   
2             0        0              0           0            1           1   
3             0        0              0           0            1           0   
4             0        0              0           0            1           0   

   Domain_End  iFrame  Mouse_Over  Right_Click  Web_Forwards  Label  
0           0       0           0            1             0      1  
1           1       0           0            1             1      0  
2           1       0           0            1             0      0  
3           1       0           0            1             0      0  
4           0       0           0            1             0      1

In [ ]:
X = data.drop(['Domain', 'Label'], axis=1)

In [ ]:
X.head()

Have_IP  Have_At  URL_Length  URL_Depth  Redirection  https_Domain  \
0        0        0           1          2            0             0   
1        0        0           1          3            0             0   
2        0        0           1          1            0             0   
3        0        0           1          2            0             0   
4        0        0           1          4            0             0   

   TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  Domain_End  \
0        0              0           0            0           0           0   
1        0              0           0            1           1           1   
2        0              0           0            1           1           1   
3        0              0           0            1           0           1   
4        0              0           0            1           0           0   

   iFrame  Mouse_Over  Right_Click  Web_Forwards  
0       0           0            1             0  
1       0           0            1             1  
2       0           0            1             0  
3       0           0            1             0  
4       0           0            1             0

In [ ]:
#y=np.ravel(data['Label'])
y=np.ravel(data['Label'])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=43)

In [ ]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
# Define classifiers
classifiers = [
    LogisticRegression(),
    SVC(),
    RandomForestClassifier(),
    MLPClassifier(),
    KNeighborsClassifier(),
    DecisionTreeClassifier()
]

In [ ]:
# Evaluate and compare classifiers
results = {'Classifier': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1 Score': []}

for clf in classifiers:
    clf_name = clf.__class__.__name__

    # Train the classifier
    clf.fit(X_train, y_train)

    # Make predictions
    y_pred = clf.predict(X_test)

    # Calculate evaluation metrics
    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Display results
    print(f"\n{clf_name} Metrics:")
    print(f"Accuracy: {acc}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")
    print("Confusion Matrix:")
    print(cm)

    # Store results for comparison
    results['Classifier'].append(clf_name)
    results['Accuracy'].append(acc)
    results['Precision'].append(precision)
    results['Recall'].append(recall)
    results['F1 Score'].append(f1)


LogisticRegression Metrics:
Accuracy: 0.8056666666666666
Precision: 0.8306649146128865
Recall: 0.8056666666666666
F1 Score: 0.8014347138839767
Confusion Matrix:
[[1438   83]
 [ 500  979]]

SVC Metrics:
Accuracy: 0.8343333333333334
Precision: 0.865507159145145
Recall: 0.8343333333333334
F1 Score: 0.8303081639168897
Confusion Matrix:
[[1493   28]
 [ 469 1010]]

RandomForestClassifier Metrics:
Accuracy: 0.8593333333333333
Precision: 0.8721878934718938
Recall: 0.8593333333333333
F1 Score: 0.8578884320042307
Confusion Matrix:
[[1451   70]
 [ 352 1127]]


/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(



MLPClassifier Metrics:
Accuracy: 0.8556666666666667
Precision: 0.8661201546819742
Recall: 0.8556666666666667
F1 Score: 0.8544219684894361
Confusion Matrix:
[[1433   88]
 [ 345 1134]]

KNeighborsClassifier Metrics:
Accuracy: 0.8463333333333334
Precision: 0.8509828342370802
Recall: 0.8463333333333334
F1 Score: 0.8456679451463515
Confusion Matrix:
[[1379  142]
 [ 319 1160]]

DecisionTreeClassifier Metrics:
Accuracy: 0.859
Precision: 0.8725235201262824
Recall: 0.859
F1 Score: 0.8574828736803661
Confusion Matrix:
[[1454   67]
 [ 356 1123]]


In [ ]:
# Display comparison results
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by='Accuracy', ascending=False)
print("\nComparison of Classifiers:")
print(results_df)


Comparison of Classifiers:
               Classifier  Accuracy  Precision    Recall  F1 Score
2  RandomForestClassifier  0.859333   0.872188  0.859333  0.857888
5  DecisionTreeClassifier  0.859000   0.872524  0.859000  0.857483
3           MLPClassifier  0.855667   0.866120  0.855667  0.854422
4    KNeighborsClassifier  0.846333   0.850983  0.846333  0.845668
1                     SVC  0.834333   0.865507  0.834333  0.830308
0      LogisticRegression  0.805667   0.830665  0.805667  0.801435
